mybestsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("mycore.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycore/urls.py
from django.urls import path

from . import views

app_name = "mycore"
urlpatterns = [
    path("", views.index, name="index"),
    path("test/", views.test, name='test'),
]

mycore/models.py
from django.db import models


class Section(models.Model):
    number = models.PositiveSmallIntegerField()
    short_title = models.CharField(max_length=15, default="None")
    title = models.CharField(max_length=20)
    text = models.TextField(max_length=1000, blank=True)

    def numbered_title(self):
        return f"0{self.number}. {self.title}"

    def numbered_short_title(self):
        return f"0{self.number}. {self.short_title}"

    def __str__(self):
        return self.title


class TextSection(Section):
    """Text Section with just text (inhereted from Section)"""


class ResumeSection(Section):
    """Resume Section with text (inhereted from Section) and ResumeEntries"""


class ResumeEntry(models.Model):
    section = models.ForeignKey(ResumeSection, on_delete=models.CASCADE)
    position = models.CharField(max_length=50)
    workplace = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True, default=None)
    description = models.TextField(max_length=1000, blank=True)
    link = models.CharField(max_length=200, null=True, blank=True, default=None)
    link_text = models.CharField(max_length=200, null=True, blank=True, default=None)


class ProjectSection(Section):
    """Resume Section with text (inhereted from Section) and ResumeEntries"""


class ProjectEntry(models.Model):
    section = models.ForeignKey(ProjectSection, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000, blank=True)
    link = models.CharField(max_length=200)
    link_text = models.CharField(max_length=200)


class ContactSection(Section):
    email = models.EmailField()


class PublicationsSection(Section):
    """Publications"""


class Publication(models.Model):
    section = models.ForeignKey(PublicationsSection, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    authors = models.CharField(max_length=100)
    journal = models.CharField(max_length=100)
    doi = models.CharField(max_length=50, null=True, blank=True, default=None)


class Title(models.Model):
    main_text = models.CharField(max_length=50)
    secondary_text = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        # To ensure only one instance exists, delete all existing instances before saving
        self.__class__.objects.exclude(pk=self.pk).delete()
        super(Title, self).save(*args, **kwargs)


class SiteButton(models.Model):
    number = models.PositiveSmallIntegerField()
    text = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    icon = models.FileField(upload_to="sitebuttons")

    def __str__(self):
        return self.text


class SiteSettings(models.Model):
    push_static = models.BooleanField(default=False)

    @classmethod
    def get_sitewide_settings(cls):
        # Get the single instance or create it if it doesn't exist
        settings, created = cls.objects.get_or_create(pk=1)
        return settings

    def save(self, *args, **kwargs):
        # To ensure only one instance exists, delete all existing instances before saving
        self.__class__.objects.exclude(pk=self.pk).delete()
        super(SiteSettings, self).save(*args, **kwargs)

mycore/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic

from .models import (ContactSection, ProjectSection, PublicationsSection,
                     ResumeSection, SiteButton, TextSection, Title)


def get_index_context():
    context = {}
    # Get all types of sections
    text_sections = list(TextSection.objects.all())
    resume_sections = list(ResumeSection.objects.all())
    project_sections = list(ProjectSection.objects.all())
    contact_sections = list(ContactSection.objects.all())
    publications_sections = list(PublicationsSection.objects.all())
    sections = (
        text_sections + resume_sections + project_sections + contact_sections + publications_sections
    )
    sections = sorted(sections, key=lambda x: x.number, reverse=False)
    context["section_list"] = sections
    # Get page title
    context["title"] = Title.objects.first()
    # Get SiteButtons
    context["sitebuttons"] = sorted(SiteButton.objects.all(), key=lambda x: x.number)
    return context


def index(request):
    context = get_index_context()
    return render(request, "mycore/index.html", context)


def test(request):
    return render(request, "mycore/test2.html", {})

mycore/templates/mycore/contact_section.html
{% load custom_tags %}

<p>{{ section.text|markdown_to_html|safe }}</p>
<p>Email: {{ section.email }}</p>

mycore/templates/mycore/index.html
{% load static %}
{% load custom_tags %}

<head>
    <title>André Patrício</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'mycore/theme.css' %}">
    <link rel="stylesheet" href="{% static 'mycore/style.css' %}">
</head>


<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <!-- <a class="navbar-brand">My Website</a> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% for section in section_list %}
                    <li class="nav-item">
                        <a class="nav-link scroll-link" href="#" data-target="{{section.short_title}}"> {{ section.numbered_short_title }} </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </nav>

    <div class="fullscreen-container">
        <div class="centered-text">
            <h1 class="h1-big">{{ title.main_text }}</h1>
            <p class="p-big">{{ title.secondary_text }}</p>
        </div>
    </div>

    {% for section in section_list %}
        <div data-id="{{section.short_title}}" class="fullscreen-container">
            <div class="{% cycle 'align-left' 'align-right' %} hard-width text-size-small p-medium-section">
                <h1>{{ section.numbered_title }}</h1> <br>
                {% if section|is_instance:"TextSection" %}
                    {% render_text_section section %}
                {% elif section|is_instance:"ResumeSection" %}
                    {% render_resume_section section %}
                {% elif section|is_instance:"ProjectSection" %}
                    {% render_project_section section %}
                {% elif section|is_instance:"PublicationsSection" %}
                    {% render_publications_section section %}
                {% elif section|is_instance:"ContactSection" %}
                    {% render_contact_section section %}
                {% else %}
                    <p>"Else Section"</p>
                {% endif %}
            </div>
        </div>
    {% endfor %}


    <div class="container">
        <ul class="buttons-list">
            {% for sbutton in sitebuttons %}
                <li>
                    <input class="small-image" type="image" src={{sbutton.icon.url}} alt="{{sbutton.text}}" onclick="openURLInNewTab('{{sbutton.url}}')"> <br>
                </li>
            {% endfor %}
        </ul>
    </div>


    <!-- "Back to the Top" button -->
    <button onclick="topFunction()" id="back-to-top" type="button" class="btn btn-light">Back to Top</button>

    <!-- Include Bootstrap JS (jQuery and Popper.js required) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'mycore/script.js' %}"></script>

</body>

mycore/templates/mycore/project_section.html
{% load custom_tags %}

<p>{{ section.text|markdown_to_html|safe }}</p>
<br>
<div id="accordion">
    {% for entry in section.projectentry_set.all %}
    <div class="card">
        <div class="card-header" id="heading_project{{entry.id}}">
            <h5 class="mb-0">
                <button class="btn btn-link text-size-medium align-left" data-toggle="collapse"
                    data-target="#collapse_project{{entry.id}}" aria-expanded="true" aria-controls="collapse{{entry.id}}">
                    {{entry.title}}
                </button>
            </h5>
        </div>
        <div id="collapse_project{{entry.id}}" class="collapse" aria-labelledby="heading_project{{entry.id}}" data-parent="#accordion">
            <div class="card-body align-left">
                {{ entry.description|markdown_to_html|safe }} <br>
                <a href="{{ entry.link }}" target="_blank"> {{entry.link_text}} </a> <br>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

mycore/templates/mycore/publications_section.html
{% load custom_tags %}

<p>{{ section.text|markdown_to_html|safe }}</p>
<br>
<div class="container text-center">
    <ul class="list-group">
        {% for publication in section.publication_set.all %}
            <li class="list-group-item">
                <b>{{ publication.title }}</b> <br>
                {{ publication.journal }} - <a href={{publication.doi}}> DOI </a>  <br>
            </li>
        {% endfor %}
    </ul>
</div>

mycore/templates/mycore/resume_section.html
{% load custom_tags %}


<p>{{ section.text|markdown_to_html|safe }}</p>
<br>
<div id="accordion">
    {% for entry in section.resumeentry_set.all %}
    <div class="card">
        <div class="card-header" id="heading{{entry.id}}">
            <h5 class="mb-0">
                <button class="btn btn-link text-size-medium align-left" data-toggle="collapse"
                    data-target="#collapse{{entry.id}}" aria-expanded="true" aria-controls="collapse{{entry.id}}">
                    {{entry.position}} @ {{entry.workplace}}
                </button>
            </h5>
        </div>
        <div id="collapse{{entry.id}}" class="collapse" aria-labelledby="heading{{entry.id}}" data-parent="#accordion">
            <div class="card-body align-left">
                {{ entry.start_date|date:"F Y" }} - {% if entry.end_date %}{{ entry.end_date|date:"F Y" }}{%else%}Current{% endif %} <br><br>
                {{ entry.description|markdown_to_html|safe }}
                <br>
                {% if entry.link %}
                    <a href="{{ entry.link }}" target="_blank"> {{entry.link_text}} </a> <br>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

mycore/templates/mycore/test.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'mycore/test_style.css' %}">
</head>


<body>

    <section class="wrapper">
        <div class="container">
          <div class="row">
            <div class="col text-center mb-5">
               <h1 class="display-4 font-weight-bolder">Bootstrap 4 Cards With Background Image</h1>
        <p class="lead">Lorem ipsum dolor sit amet at enim hac integer volutpat maecenas pulvinar. </p>
            </div>
          </div>
        <div class="row">
       <div class="col-sm-12 col-md-6 col-lg-4 mb-4"><div class="card text-dark card-has-bg click-col" style="background-image:url('https://source.unsplash.com/600x900/?tech,street');">
               <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tech,street" alt="Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?">
              <div class="card-img-overlay d-flex flex-column">
               <div class="card-body">
                  <small class="card-meta mb-2">Thought Leadership</small>
                  <h4 class="card-title mt-0 "><a class="text-dark" herf="https://creativemanner.com">Web Developmet Lorem Ipsum Sit Amet Consectetur dipisi?</a></h4>
                 <small><i class="far fa-clock"></i> October 15, 2020</small>
                </div>
                <div class="card-footer">
                 <div class="media">
        <img class="mr-3 rounded-circle" src="https://assets.codepen.io/460692/internal/avatars/users/default.png?format=auto&version=1688931977&width=80&height=80" alt="Generic placeholder image" style="max-width:50px">
        <div class="media-body">
          <h6 class="my-0 text-dark d-block">Oz Coruhlu</h6>
           <small>Director of UI/UX</small>
        </div>
      </div>
                </div>
              </div>
            </div></div>
           <div class="col-sm-12 col-md-6 col-lg-4 mb-4"><div class="card text-dark card-has-bg click-col" style="background-image:url('https://source.unsplash.com/600x900/?tree,nature');">
               <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tree,nature" alt="Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?">
              <div class="card-img-overlay d-flex flex-column">
               <div class="card-body">
                  <small class="card-meta mb-2">Thought Leadership</small>
                  <h4 class="card-title mt-0 "><a class="text-dark" herf="https://creativemanner.com">Creative Manner Lorem Ipsum Sit Amet Consectetur dipisi?</a></h4>
                 <small><i class="far fa-clock"></i> October 15, 2020</small>
                </div>
                <div class="card-footer">
                 <div class="media">
        <img class="mr-3 rounded-circle" src="https://assets.codepen.io/460692/internal/avatars/users/default.png?format=auto&version=1688931977&width=80&height=80" alt="Generic placeholder image" style="max-width:50px">
        <div class="media-body">
          <h6 class="my-0 text-dark d-block">Oz Coruhlu</h6>
           <small>Director of UI/UX</small>
        </div>
      </div>
                </div>
              </div>
            </div></div>
        <div class="col-sm-12 col-md-6 col-lg-4 mb-4"><div class="card text-dark card-has-bg click-col" style="background-image:url('https://source.unsplash.com/600x900/?computer,design');">
               <img class="card-img d-none" src="https://source.unsplash.com/600x900/?computer,design" alt="Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?">
              <div class="card-img-overlay d-flex flex-column">
               <div class="card-body">
                  <small class="card-meta mb-2">Thought Leadership</small>
                  <h4 class="card-title mt-0 "><a class="text-dark" herf="https://creativemanner.com">Design Studio Lorem Ipsum Sit Amet Consectetur dipisi?</a></h4>
                 <small><i class="far fa-clock"></i> October 15, 2020</small>
                </div>
                <div class="card-footer">
                 <div class="media">
        <img class="mr-3 rounded-circle" src="https://assets.codepen.io/460692/internal/avatars/users/default.png?format=auto&version=1688931977&width=80&height=80" alt="Generic placeholder image" style="max-width:50px">
        <div class="media-body">
          <h6 class="my-0 text-dark d-block">Oz Coruhlu</h6>
           <small>Director of UI/UX</small>
        </div>
      </div>
                </div>
              </div>
            </div></div>
         
          <div class="col-sm-12 col-md-6 col-lg-4 mb-4"><div class="card text-dark card-has-bg click-col" style="background-image:url('https://source.unsplash.com/600x900/?tech,street');">
               <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tech,street" alt=" Lorem Ipsum Sit Amet Consectetur dipisi?">
              <div class="card-img-overlay d-flex flex-column">
               <div class="card-body">
                  <small class="card-meta mb-2">Thought Leadership</small>
                  <h4 class="card-title mt-0 "><a class="text-dark" herf="https://creativemanner.com">UI/UX Design Lorem Ipsum Sit Amet Consectetur dipisi?</a></h4>
                 <small><i class="far fa-clock"></i> October 15, 2020</small>
                </div>
                <div class="card-footer">
                 <div class="media">
        <img class="mr-3 rounded-circle" src="https://assets.codepen.io/460692/internal/avatars/users/default.png?format=auto&version=1688931977&width=80&height=80" alt="Generic placeholder image" style="max-width:50px">
        <div class="media-body">
          <h6 class="my-0 text-dark d-block">Oz Coruhlu</h6>
           <small>Director of UI/UX</small>
        </div>
      </div>
                </div>
              </div>
            </div></div>
           <div class="col-sm-12 col-md-6 col-lg-4 mb-4"><div class="card text-dark card-has-bg click-col" style="background-image:url('https://source.unsplash.com/600x900/?tree,nature');">
               <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tree,nature" alt="Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?">
              <div class="card-img-overlay d-flex flex-column">
               <div class="card-body">
                  <small class="card-meta mb-2">Thought Leadership</small>
                  <h4 class="card-title mt-0 "><a class="text-dark" herf="https://creativemanner.com">Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?</a></h4>
                 <small><i class="far fa-clock"></i> October 15, 2020</small>
                </div>
                <div class="card-footer">
                 <div class="media">
        <img class="mr-3 rounded-circle" src="https://assets.codepen.io/460692/internal/avatars/users/default.png?format=auto&version=1688931977&width=80&height=80" alt="Generic placeholder image" style="max-width:50px">
        <div class="media-body">
          <h6 class="my-0 text-dark d-block">Oz Coruhlu</h6>
           <small>Director of UI/UX</small>
        </div>
      </div>
                </div>
              </div>
            </div></div>
        <div class="col-sm-12 col-md-6 col-lg-4 mb-4"><div class="card text-dark card-has-bg click-col" style="background-image:url('https://source.unsplash.com/600x900/?computer,design');">
               <img class="card-img d-none" src="https://source.unsplash.com/600x900/?computer,design" alt="Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?">
              <div class="card-img-overlay d-flex flex-column">
               <div class="card-body">
                  <small class="card-meta mb-2">Thought Leadership</small>
                  <h4 class="card-title mt-0 "><a class="text-dark" herf="https://creativemanner.com">Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?</a></h4>
                 <small><i class="far fa-clock"></i> October 15, 2020</small>
                </div>
                <div class="card-footer">
                 <div class="media">
        <img class="mr-3 rounded-circle" src="https://assets.codepen.io/460692/internal/avatars/users/default.png?format=auto&version=1688931977&width=80&height=80" alt="Generic placeholder image" style="max-width:50px">
        <div class="media-body">
          <h6 class="my-0 text-dark d-block">Oz Coruhlu</h6>
           <small>Director of UI/UX</small>
        </div>
      </div>
                </div>
              </div>
            </div></div>
        
      </div>
        
      </div>
      </section>
      

</body>

mycore/templates/mycore/test2.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'mycore/test2_style.css' %}">
</head>

<body>
<div class="container mx-auto mt-4">
    <div class="row">
      <div class="col-md-4">
        <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
         <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn "><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
      </div>    
         <div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn  mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
      </div>    
            <div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn "><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
    </div>
      
      <div class="col-md-4">
        <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
         <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
      </div>    
         <div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
      </div>    
            <div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
    </div>
      
      <div class="col-md-4">
        <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
         <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
      </div>    
         <div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
      </div>    
            <div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn btn-primary"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
    </div>
      
      <div class="col-md-4">
        <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
         <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
      </div>    
         <div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
      </div>    
            <div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a>
      <a href="#" class="btn"><i class="fab fa-github"></i> Github</a>
    </div>
    </div>
    </div>
  </div>
    </div>

</body>

mycore/templates/mycore/text_section.html
{% load custom_tags %}

<p>{{ section.text|markdown_to_html|safe }}</p>